version: '3.8'

services:
  db:
    image: postgres:14
    container_name: jog_match_db
    ports:
      - 5433:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jog_match
    restart: always